#!/usr/bin/env python3
"""Cheap, deterministic Claude Code guards for the GNFS repository."""

from __future__ import annotations

import json
import os
from pathlib import Path
import re
import subprocess
import sys


GENERATED_ROOTS = {"build", "xcode-build", ".worktrees"}
GENERATED_ROOT_PATTERNS = (
    re.compile(r"^build-.+"),
    re.compile(r"^cmake-build-.+"),
)


def read_input() -> dict:
    try:
        value = json.load(sys.stdin)
    except (json.JSONDecodeError, OSError):
        return {}
    return value if isinstance(value, dict) else {}


def project_root() -> Path:
    configured = os.environ.get("CLAUDE_PROJECT_DIR")
    if configured:
        return Path(configured).expanduser().resolve()
    return Path(__file__).resolve().parents[2]


def emit(payload: dict) -> None:
    print(json.dumps(payload, ensure_ascii=False))


def generated_path_reason(path_value: object, root: Path) -> str | None:
    if not isinstance(path_value, str) or not path_value.strip():
        return None

    candidate = Path(path_value).expanduser()
    if not candidate.is_absolute():
        candidate = root / candidate

    try:
        relative = candidate.resolve(strict=False).relative_to(root)
    except ValueError:
        return None

    parts = relative.parts
    if not parts:
        return None

    first = parts[0]
    if first in GENERATED_ROOTS or any(pattern.fullmatch(first) for pattern in GENERATED_ROOT_PATTERNS):
        return f"{relative} is generated or worktree-managed output"
    if len(parts) >= 2 and parts[:2] == (".claude", "worktrees"):
        return f"{relative} is a Claude-managed worktree"
    if "CMakeFiles" in parts:
        return f"{relative} is generated by CMake"
    return None


def handle_pre_tool_use(data: dict, root: Path) -> None:
    if data.get("tool_name") not in {"Edit", "Write"}:
        return

    tool_input = data.get("tool_input")
    file_path = tool_input.get("file_path") if isinstance(tool_input, dict) else None
    reason = generated_path_reason(file_path, root)
    if reason is None:
        return

    emit(
        {
            "hookSpecificOutput": {
                "hookEventName": "PreToolUse",
                "permissionDecision": "deny",
                "permissionDecisionReason": (
                    f"Blocked direct edit: {reason}. Edit source/configuration files and regenerate output instead."
                ),
            }
        }
    )


def handle_stop(data: dict, root: Path) -> None:
    if data.get("stop_hook_active") is True:
        return

    checker = root / "scripts" / "check_harness.py"
    if not checker.is_file():
        emit(
            {
                "decision": "block",
                "reason": "GNFS Harness checker is missing at scripts/check_harness.py.",
            }
        )
        return

    try:
        result = subprocess.run(
            [sys.executable, str(checker), "--quiet"],
            cwd=root,
            text=True,
            capture_output=True,
            timeout=8,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        emit(
            {
                "decision": "block",
                "reason": f"GNFS Harness self-check could not complete: {exc}",
            }
        )
        return

    if result.returncode == 0:
        return

    details = (result.stderr or result.stdout or "unknown validation failure").strip()
    emit(
        {
            "decision": "block",
            "reason": (
                "GNFS Harness self-check failed. Fix the deterministic configuration errors before stopping:\n"
                + details[:3000]
            ),
        }
    )


def main() -> None:
    data = read_input()
    event = data.get("hook_event_name")
    root = project_root()
    if event == "PreToolUse":
        handle_pre_tool_use(data, root)
    elif event == "Stop":
        handle_stop(data, root)


if __name__ == "__main__":
    main()
