# CMake generated Testfile for 
# Source directory: /Users/admin/Desktop/Documents/GNFS
# Build directory: /Users/admin/Desktop/Documents/GNFS/build-release
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[SmallVector]=] "/Users/admin/Desktop/Documents/GNFS/build-release/test_small_vector")
set_tests_properties([=[SmallVector]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/admin/Desktop/Documents/GNFS/CMakeLists.txt;198;add_test;/Users/admin/Desktop/Documents/GNFS/CMakeLists.txt;0;")
add_test([=[Integer]=] "/Users/admin/Desktop/Documents/GNFS/build-release/test_integer")
set_tests_properties([=[Integer]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/admin/Desktop/Documents/GNFS/CMakeLists.txt;204;add_test;/Users/admin/Desktop/Documents/GNFS/CMakeLists.txt;0;")
add_test([=[ThreadPool]=] "/Users/admin/Desktop/Documents/GNFS/build-release/test_thread_pool")
set_tests_properties([=[ThreadPool]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/admin/Desktop/Documents/GNFS/CMakeLists.txt;210;add_test;/Users/admin/Desktop/Documents/GNFS/CMakeLists.txt;0;")
add_test([=[FactorBase]=] "/Users/admin/Desktop/Documents/GNFS/build-release/test_factor_base")
set_tests_properties([=[FactorBase]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/admin/Desktop/Documents/GNFS/CMakeLists.txt;216;add_test;/Users/admin/Desktop/Documents/GNFS/CMakeLists.txt;0;")
add_test([=[SpecialQ]=] "/Users/admin/Desktop/Documents/GNFS/build-release/test_special_q")
set_tests_properties([=[SpecialQ]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/admin/Desktop/Documents/GNFS/CMakeLists.txt;222;add_test;/Users/admin/Desktop/Documents/GNFS/CMakeLists.txt;0;")
add_test([=[LatticeSieve]=] "/Users/admin/Desktop/Documents/GNFS/build-release/test_lattice_sieve")
set_tests_properties([=[LatticeSieve]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/admin/Desktop/Documents/GNFS/CMakeLists.txt;228;add_test;/Users/admin/Desktop/Documents/GNFS/CMakeLists.txt;0;")
add_test([=[RelationCollector]=] "/Users/admin/Desktop/Documents/GNFS/build-release/test_relation_collector")
set_tests_properties([=[RelationCollector]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/admin/Desktop/Documents/GNFS/CMakeLists.txt;234;add_test;/Users/admin/Desktop/Documents/GNFS/CMakeLists.txt;0;")
add_test([=[SieveIntegration]=] "/Users/admin/Desktop/Documents/GNFS/build-release/test_sieve_basic")
set_tests_properties([=[SieveIntegration]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/admin/Desktop/Documents/GNFS/CMakeLists.txt;240;add_test;/Users/admin/Desktop/Documents/GNFS/CMakeLists.txt;0;")
add_test([=[Cofactor]=] "/Users/admin/Desktop/Documents/GNFS/build-release/test_cofactor")
set_tests_properties([=[Cofactor]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/admin/Desktop/Documents/GNFS/CMakeLists.txt;246;add_test;/Users/admin/Desktop/Documents/GNFS/CMakeLists.txt;0;")
add_test([=[LinearAlgebra]=] "/Users/admin/Desktop/Documents/GNFS/build-release/test_linalg")
set_tests_properties([=[LinearAlgebra]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/admin/Desktop/Documents/GNFS/CMakeLists.txt;252;add_test;/Users/admin/Desktop/Documents/GNFS/CMakeLists.txt;0;")
add_test([=[SquareRoot]=] "/Users/admin/Desktop/Documents/GNFS/build-release/test_sqrt")
set_tests_properties([=[SquareRoot]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/admin/Desktop/Documents/GNFS/CMakeLists.txt;258;add_test;/Users/admin/Desktop/Documents/GNFS/CMakeLists.txt;0;")
add_test([=[GNFS_E2E]=] "/Users/admin/Desktop/Documents/GNFS/build-release/test_gnfs_e2e")
set_tests_properties([=[GNFS_E2E]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/admin/Desktop/Documents/GNFS/CMakeLists.txt;264;add_test;/Users/admin/Desktop/Documents/GNFS/CMakeLists.txt;0;")
add_test([=[Murphy]=] "/Users/admin/Desktop/Documents/GNFS/build-release/test_murphy")
set_tests_properties([=[Murphy]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/admin/Desktop/Documents/GNFS/CMakeLists.txt;271;add_test;/Users/admin/Desktop/Documents/GNFS/CMakeLists.txt;0;")
add_test([=[Kleinjung]=] "/Users/admin/Desktop/Documents/GNFS/build-release/test_kleinjung")
set_tests_properties([=[Kleinjung]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/admin/Desktop/Documents/GNFS/CMakeLists.txt;277;add_test;/Users/admin/Desktop/Documents/GNFS/CMakeLists.txt;0;")
add_test([=[KleinjungLarge]=] "/Users/admin/Desktop/Documents/GNFS/build-release/test_kleinjung_large")
set_tests_properties([=[KleinjungLarge]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/admin/Desktop/Documents/GNFS/CMakeLists.txt;283;add_test;/Users/admin/Desktop/Documents/GNFS/CMakeLists.txt;0;")
add_test([=[FactorWithKleinjung]=] "/Users/admin/Desktop/Documents/GNFS/build-release/test_factor_with_kleinjung")
set_tests_properties([=[FactorWithKleinjung]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/admin/Desktop/Documents/GNFS/CMakeLists.txt;289;add_test;/Users/admin/Desktop/Documents/GNFS/CMakeLists.txt;0;")
add_test([=[SqrtDebug]=] "/Users/admin/Desktop/Documents/GNFS/build-release/test_sqrt_debug")
set_tests_properties([=[SqrtDebug]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/admin/Desktop/Documents/GNFS/CMakeLists.txt;295;add_test;/Users/admin/Desktop/Documents/GNFS/CMakeLists.txt;0;")
add_test([=[GNFS_Progressive_L1]=] "/Users/admin/Desktop/Documents/GNFS/build-release/test_gnfs_progressive" "1" "1")
set_tests_properties([=[GNFS_Progressive_L1]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/admin/Desktop/Documents/GNFS/CMakeLists.txt;302;add_test;/Users/admin/Desktop/Documents/GNFS/CMakeLists.txt;0;")
add_test([=[GNFS_Progressive_L2]=] "/Users/admin/Desktop/Documents/GNFS/build-release/test_gnfs_progressive" "2" "2")
set_tests_properties([=[GNFS_Progressive_L2]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/admin/Desktop/Documents/GNFS/CMakeLists.txt;303;add_test;/Users/admin/Desktop/Documents/GNFS/CMakeLists.txt;0;")
add_test([=[Params]=] "/Users/admin/Desktop/Documents/GNFS/build-release/test_params")
set_tests_properties([=[Params]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/admin/Desktop/Documents/GNFS/CMakeLists.txt;311;add_test;/Users/admin/Desktop/Documents/GNFS/CMakeLists.txt;0;")
add_test([=[IntPolynomial]=] "/Users/admin/Desktop/Documents/GNFS/build-release/test_int_polynomial")
set_tests_properties([=[IntPolynomial]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/admin/Desktop/Documents/GNFS/CMakeLists.txt;318;add_test;/Users/admin/Desktop/Documents/GNFS/CMakeLists.txt;0;")
add_test([=[Filter]=] "/Users/admin/Desktop/Documents/GNFS/build-release/test_filter")
set_tests_properties([=[Filter]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/admin/Desktop/Documents/GNFS/CMakeLists.txt;325;add_test;/Users/admin/Desktop/Documents/GNFS/CMakeLists.txt;0;")
add_test([=[Regressions]=] "/Users/admin/Desktop/Documents/GNFS/build-release/test_regressions")
set_tests_properties([=[Regressions]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/admin/Desktop/Documents/GNFS/CMakeLists.txt;332;add_test;/Users/admin/Desktop/Documents/GNFS/CMakeLists.txt;0;")
add_test([=[PolynomialContext]=] "/Users/admin/Desktop/Documents/GNFS/build-release/test_polynomial_context")
set_tests_properties([=[PolynomialContext]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/admin/Desktop/Documents/GNFS/CMakeLists.txt;339;add_test;/Users/admin/Desktop/Documents/GNFS/CMakeLists.txt;0;")
add_test([=[BaseM]=] "/Users/admin/Desktop/Documents/GNFS/build-release/test_base_m")
set_tests_properties([=[BaseM]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/admin/Desktop/Documents/GNFS/CMakeLists.txt;346;add_test;/Users/admin/Desktop/Documents/GNFS/CMakeLists.txt;0;")
add_test([=[PolynomialOptimizer]=] "/Users/admin/Desktop/Documents/GNFS/build-release/test_polynomial_optimizer")
set_tests_properties([=[PolynomialOptimizer]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/admin/Desktop/Documents/GNFS/CMakeLists.txt;353;add_test;/Users/admin/Desktop/Documents/GNFS/CMakeLists.txt;0;")
add_test([=[ClassGroup]=] "/Users/admin/Desktop/Documents/GNFS/build-release/test_class_group")
set_tests_properties([=[ClassGroup]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/admin/Desktop/Documents/GNFS/CMakeLists.txt;360;add_test;/Users/admin/Desktop/Documents/GNFS/CMakeLists.txt;0;")
add_test([=[EdgeCases]=] "/Users/admin/Desktop/Documents/GNFS/build-release/test_edge_cases")
set_tests_properties([=[EdgeCases]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/admin/Desktop/Documents/GNFS/CMakeLists.txt;367;add_test;/Users/admin/Desktop/Documents/GNFS/CMakeLists.txt;0;")
add_test([=[Integration]=] "/Users/admin/Desktop/Documents/GNFS/build-release/test_integration")
set_tests_properties([=[Integration]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/admin/Desktop/Documents/GNFS/CMakeLists.txt;374;add_test;/Users/admin/Desktop/Documents/GNFS/CMakeLists.txt;0;")
